### PR TITLE
Add test-e2e-image target to run test on operator image

### PR DESCRIPTION
**Pull request by pratikjagrut**
This is for running e2e test in cluster way, an alternative to run tests locally on the operator.

### CODE REVIEW

**Comment by DhritiShikhar** [comment]
@pratikjagrut Is there a story/ task in Jira for this?

**Comment by pratikjagrut** [comment]
> @pratikjagrut Is there a story/ task in Jira for this?
No, me @pmacik and @ldimaggi had a discussion over this. And thought its good to keep this target too.

**Comment by pratikjagrut** [comment]
@ldimaggi and @pmacik can you also take a look.

**Comment by pratikjagrut** [comment]
@DhritiShikhar can you merge it?

**Pull request merged**
