### PR TITLE
Updates deploy cr

### PR DESCRIPTION
**Pull request by DhritiShikhar**
### Motivation

Updates deploy CR

### Changes

Updates deploy CR to include `resourceRef`

### CODE REVIEW

**Comment by Avni-Sharma** [comment]
The alm-examples generated under the CSV consider the CR under deploy/cr.yaml which is failing at the community-operators side.

**Comment by sbose78** [comment]
We would still need to fix the issue with resourceRef being mandatory, right?

**Comment by DhritiShikhar** [comment]
@sbose78 I know, but at least we can get the community side PR merged first. 
Last time you mentioned that the Community side PR should not be holding an error for a long time.

**Comment by sbose78** [comment]
Dhriti, right! Helps bump up community-operators PR up their review queue :-)

**Pull request merged**
