### PR TITLE
Add a choice of installing SBO either from community or master in examples

### PR DESCRIPTION
**Pull request by pmacik**
### Motivation

Currently, the examples use the version of the SBO installed from `community-operators`. I was not easy to try those examples with the latest version of the examples that are built from `master`.

Providing means to run those examples with the latest `master` version of SBO also supports automated tests that implement the example's scenarios.

This is a dependency for #441.

### Changes

This PR adds make target for installing the latest SBO version from `master` using a custom `OperatorSource` and renames the current make targets (for the community version) by adding `community` suffix.

### Testing

Tests introduced in #441 use this update.

### CODE REVIEW

**Comment by sbose78** [comment]
If I had to do manually with yamls, how would I do so?

**Comment by pmacik** [comment]
> If I had to do manually with yamls, how would I do so?

@sbose78 Same as before. I added the instructions for manual steps into the docs, if that's what you were asking for

**Pull request merged**
