### PR TITLE
Remove dead code related to relationship annotations

### PR DESCRIPTION
**Pull request by isutton**
### Motivation

This PR removes code that should've been deleted in #596.

For further more details refer the CONTRIBUTING.md

### CODE REVIEW

**Comment by DhritiShikhar** [comment]
The e2e tests are failing on the PR.

**Comment by DhritiShikhar** [comment]
@isutton Can you please move this PR from DRAFT. So, that it can be merged?

**Comment by DhritiShikhar** [comment]
Also, @isutton You need to rebase this PR. :)

**Comment by DhritiShikhar** [comment]
@isutton The acceptance tests are failing on the PR.
Can we get this merged?

**Comment by pedjak** [comment]
> The acceptance tests are failing on the PR.
Can we get this merged?

@DhritiShikhar Tests should be green to merge any PR.

**Comment by DhritiShikhar** [comment]
@pedjak I know that. 
I meant - can we bring this PR to a "merge-able" state?

**Pull request merged**
