### PR TITLE
Add remaining permutations to the SBR e2e test.

### PR DESCRIPTION
**Pull request by pmacik**
This PR:
* Adds the 4 remaining permutations of the E2E test scenario for Service Binding
* Resolves the [APPSVC-126](https://jira.coreos.com/browse/APPSVC-126)

### CODE REVIEW

**Comment by pmacik** [comment]
The e2e tests fails due to:
* https://github.com/redhat-developer/service-binding-operator/issues/234
* `can't find DATABASE_SECRET_USER in data`
issues in the operator.

**Comment by sbose78** [comment]
> can't find DATABASE_SECRET_USER in data

#244


Since those are different failures, I'm taking this in.

**Pull request merged**
