### PR TITLE
Make the RHEL Dockerfile the primary Dockerfile

### PR DESCRIPTION
**Pull request by sbose78**
- Removed `Dockerfile`
- Renamed `Dockerfile.rhel` to `Dockerfile`
- This branch has triggered a build https://quay.io/repository/redhat-developer/app-binding-operator/build/d1916965-2fdc-4c16-ac45-11dec33f7577 which will generate `quay.io/redhat-developer/app-binding-operator:rhel8-dockerfile`

### CODE REVIEW

**Comment by sbose78** [comment]
> quay.io/redhat-developer/app-binding-operator:rhel8-dockerfile

@Avni-Sharma Could you validate this specific tagged image?

**Comment by Avni-Sharma** [comment]
> > quay.io/redhat-developer/app-binding-operator:rhel8-dockerfile
> 
> @Avni-Sharma Could you validate this specific tagged image?

it is running
/lgtm

**Comment by sbose78** [comment]
/hold

Thanks @Avni-Sharma 
We'll let `Dockerfile.rhel` be as is. Will remove the `Dockerfile`

**Comment by baijum** [comment]
We can close this PR, right?

**Comment by sbose78** [comment]
@baijum , right.

**Pull request closed without merging**
