### PR TITLE
Change channel from stable to alpha

### PR DESCRIPTION
**Pull request by Avni-Sharma**
This PR provides two channels - `dev` and `stable`. In the future, we can have these channels pointing to different ClusterServiceVersion respectively. For development purpose, we can use the dev channel and a stable release can be under the stable channel.  By default the cannel is the `dev` channel.

### CODE REVIEW

**Comment by Avni-Sharma** [comment]
> Is this is the only place channel is specified?

yes.
Also https://github.com/redhat-developer/service-binding-operator/blob/master/test/e2e/catalog_source.yaml and subscription.yaml is not needed anymore, if we are using operator source. wdyt

**Comment by sbose78** [comment]
I would prefer to have two channels

**Comment by Avni-Sharma** [comment]
cc @pmacik

**Comment by pmacik** [comment]
LGTM

**Pull request merged**
