### PR TITLE
Add shortNames to Servicebindingrequest in CRD

### PR DESCRIPTION
**Pull request by akashshinde**
Fixes https://github.com/redhat-developer/service-binding-operator/issues/135

**What this PR does**
To get created servicebindingrequest resources, we can use
`oc get sbr` 
or 
`oc get sbrs`

### CODE REVIEW

**Comment by akashshinde** [comment]
Thanks Shoubhik, I will refactor accordingly

**Comment by sbose78** [comment]
@akashshinde  Let's get this in, this is a very useful fix.

**Comment by akashshinde** [comment]
> @akashshinde Let's get this in, this is a very useful fix.

Done

**Comment by akashshinde** [comment]
> These changes would be overwritten if someone did a
> operator-sdk generate k8s
> Followed by a
> operator-sdk generate openapi
> 
> This is how you should add the short names
> [operator-framework/operator-sdk#1593](https://github.com/operator-framework/operator-sdk/issues/1593)
> 
> And then run the above two commands.

Handled here https://github.com/redhat-developer/service-binding-operator/pull/136/commits/c042dc3dad9fa8cca689e6a679c887a6253d28b2

**Pull request merged**
