### PR TITLE
Update to match OpenShift 4.3 change for sample app - nodejs_postgresql

### PR DESCRIPTION
**Pull request by ldimaggi**
Updated is needed to stay in synch with OpenShift 4.3 - Red Hat-wide we are avoiding use of DeploymentConfigs or any RedHat specific types which aren't present in Kubernetes. Hence the change to Deployments. 

And - the use of labels to facilitate service binding is discouraged - the examples should use the resourceRef elements to provide binding information. https://github.com/redhat-developer/service-binding-operator/issues/255

### CODE REVIEW

**Comment by ldimaggi** [comment]
WIP - until the PR covers all the other examples.

**Comment by ldimaggi** [comment]
Another problem to be debugged - after making the changes in this PR and running the example, the binding appears in the Topology - but there are connection failures with the database:

Screenshot from 2019-11-23 22-46-23
```

oc logs nodejs-rest-http-crud-7846b4ff6-z5mxq
Environment: 
	DEV_MODE=false
	NODE_ENV=production
	DEBUG_PORT=5858
Launching via npm...
npm info it worked if it ends with ok
npm info using npm@6.9.0
npm info using node@v10.16.3
npm info lifecycle nodejs-rest-http-crud@3.0.1~prestart: nodejs-rest-http-crud@3.0.1
npm info lifecycle nodejs-rest-http-crud@3.0.1~start: nodejs-rest-http-crud@3.0.1

> nodejs-rest-http-crud@3.0.1 start /opt/app-root/src
> node .

{ Error: connect ECONNREFUSED 127.0.0.1:5432
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1106:14)
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 5432 }


```

**Comment by ldimaggi** [comment]
All the other sample apps will require the same changes.

**Comment by pmacik** [comment]
@ldimaggi @sbose78 Please, correct me if I'm wrong but the Service Binding Operator is now part of the Community operators and so it appears in the OpenShift's `Operator Hub` out-of-the-box, right?
It that's the case, Isn't the step of installing the `OperatorSource` obsolete, now?

**Comment by ldimaggi** [comment]
+1 to Pavel's suggestion - The Service Binding Operator is now in Operatorhub - there is no need for the user to install it from the OperatorSource file. The file and the reference to it have been removed from the example through this PR. Thx!

**Pull request merged**
