### PR TITLE
announce deprecation

### PR DESCRIPTION
**Pull request by sadlerap**
# Changes

Announces SBO's deprecation.

/kind documentation

# Submitter Checklist

As the author of this PR, please check off the items in this checklist:

- [ ] [Docs](https://github.com/redhat-developer/service-binding-operator/blob/master/CONTRIBUTING.md#docs) 
  included if any changes are user facing
- [ ] [Tests](https://github.com/redhat-developer/service-binding-operator/blob/master/CONTRIBUTING.md#tests)
  included if any functionality added or changed. For bugfixes please include tests that can catch regressions
- [ ] All acceptance test scenarios included in the PR which verifies a bugfix or a requested feature reported by a non-member are tagged with `@external-feedback` tag.
- [ ] Follows the [commit message standard](https://github.com/redhat-developer/service-binding-operator/blob/master/CONTRIBUTING.md#commits)

### CODE REVIEW

**Review by baijum — APPROVED** [review]
/lgtm

**Review by filariow — APPROVED** [review]
/lgtm

**Comment by gberche-orange** [comment]
@sadlerap Where can be found the rationale for the deprecation as well as the suggested migration plan, e.g. to the service binding reference implementation at https://github.com/servicebinding/runtime  ?

**Comment by sadlerap** [comment]
I'm in the process of putting together a more comprehensive migration guide; expect that to land fairly soon.

As for why SBO is being deprecated:
- This project has largely been in maintenance mode since January 2023 (over a year ago).  We haven't added any new features since then, and we've only really put out releases whenever someone's asked for one.
- Getting this project back into a state of active development would require some effort; unfortunately, most of the former maintainers don't have a lot of bandwidth to work on this anymore.
- Speaking as someone who also works on the upstream service bindings working group: I'd rather have users concentrate on one project & implementation, not two.

**Pull request merged**
