### PR TITLE
crds: trim crd structs

### PR DESCRIPTION
**Pull request by sadlerap**
We're spending a lot of time deserializing crds.  As an attempt to reduce time and memory spent here, we should trim down the fields stored in the CRDs we need in the crd controller.

Signed-off-by: Andy Sadler <ansadler@redhat.com>

# Changes

/kind bug

# Submitter Checklist

As the author of this PR, please check off the items in this checklist:

- [ ] [Docs](https://github.com/redhat-developer/service-binding-operator/blob/master/CONTRIBUTING.md#docs) 
  included if any changes are user facing
- [ ] [Tests](https://github.com/redhat-developer/service-binding-operator/blob/master/CONTRIBUTING.md#tests)
  included if any functionality added or changed. For bugfixes please include tests that can catch regressions
- [ ] All acceptance test scenarios included in the PR which verifies a bugfix or a requested feature reported by a non-member are tagged with `@external-feedback` tag.
- [ ] Follows the [commit message standard](https://github.com/redhat-developer/service-binding-operator/blob/master/CONTRIBUTING.md#commits)

### CODE REVIEW

**Comment by sadlerap** [comment]
/hold

Awaiting acceptance & conformance tests; this may not actually get us anything.

**Comment by pmacik** [comment]
@sadlerap I guess it is not our own code that holds the data (while I find it a good idea to limit the amount of data to only what we need)... From what I saw in the cumulative allocation tree it was the `client-go`'s `dynamic` client who does (its JSON unmarshallers/decoders down the line).

**Pull request closed without merging**
