### PR TITLE
Add API for environment parameter mapping

### PR DESCRIPTION
**Pull request by Avni-Sharma**
Refer- https://jira.coreos.com/browse/ODC-1422

Add API for envVar as stated in the following CR

```
apiVersion: apps.openshift.io/v1alpha1
kind: ServiceBindingRequest
metadata:
  name: binding-request
  namespace: openshift-operators
spec:
  applicationSelector:
    matchLabels:
      connects-to: db-demo
      environment: demo
    resourceKind: DeploymentConfig
  backingSelector:
    resourceRef: db-demo
    resourceKind: databases.postgresql.baiju.dev
    resourceVersion: v1alpha1
  
  envVar:
  - Name: JDBC_CONNECTION_STRING
    Value: ${status.dbCredentials.user}:${status.dbCredentials.password}@${status.dbConnectionIP} 
```

### CODE REVIEW

**Comment by sbose78** [comment]
Do you wish to modify the CRD in this PR and then the controller in a different one?

**Comment by sbose78** [comment]
```
envVar:
  - Name: JDBC_CONNECTION_STRING
    Value: ${status.dbCredentials.user}:${status.dbCredentials.password}@${status.dbConnectionIP} 
```
Structure looks right to me.

**Comment by Avni-Sharma** [comment]
> Do you wish to modify the CRD in this PR and then the controller in a different one?

yeah. Planned to send API in one and the controller logic in the other.

**Pull request closed without merging**
