### PR TITLE
Roadmap for v1

### PR DESCRIPTION
**Pull request by isutton**
This PR defines the Roadmap for v1.

It contains an example use case from MVP to application decoupling that'll be used to guide the scope.

### CODE REVIEW

**Comment by sbose78** [comment]
Thanks a ton for getting this started. Are you using something as a reference for organizing the roadmap? I found https://github.com/tektoncd/pipeline/blob/master/roadmap-2019.md

**Comment by isutton** [comment]
Thanks for the reference! 

I will start a roadmap document based on Tekton's.

**Comment by sbose78** [comment]
API changes look good to me.

Things to do:

- Generic binding - in progress
- custom env var - can we specify which backing service ? ( important )
-  maybe it's just Workload --> Service ?


Workload ---> Service

```
apiVersion: apps.openshift.io/v1
kind: ServiceBinding
metadata:
  name: webshop
spec:
  applications:
  - group: apps
    version: v1
    resource: deployments
    name: nodefrontendapp
  services:
  - group: 
    version: corev1
    kind: Service
    name: GolangApp
  - group: 
    version: corev1
    kind: ConfigMap
    name: BackendServiceCredentials
```

**Comment by sbose78** [comment]
Given this is stale, I'll close this. We'll re-open when we work on this later on.

**Pull request closed without merging**
