### PR TITLE
Update roadmap link

### PR DESCRIPTION
**Pull request by jasperchui**
### Motivation

Update readme with roadmap details. Reorganized sections to be more readable.

### Changes

- Updated readme with link to roadmap (milestone)
- Reorganized sections of the readme

### Testing

N/A

For further more details refer the CONTRIBUTING.md

### CODE REVIEW

**Review by pedjak — APPROVED** [review]

**Comment by pedjak** [comment]
please sign you commit

**Comment by jasperchui** [comment]
> please sign you commit

Done.  Please review. Thanks.

**Comment by pedjak** [comment]
you have in your branch commits that are already present in the master, this needs to be cleanedup.

**Review by slemeur — APPROVED** [review]

**Pull request merged**
