### PR TITLE
owners: add @shruthihub as approver & reviewer

### PR DESCRIPTION
**Pull request by sadlerap**
Signed-off-by: Andy Sadler <ansadler@redhat.com>

# Changes

Adds @shruthihub as both an approver and a reviewer for SBO.

# Submitter Checklist

As the author of this PR, please check off the items in this checklist:

- [ ] [Docs](https://github.com/redhat-developer/service-binding-operator/blob/master/CONTRIBUTING.md#docs) 
  included if any changes are user facing
- [ ] [Tests](https://github.com/redhat-developer/service-binding-operator/blob/master/CONTRIBUTING.md#tests)
  included if any functionality added or changed. For bugfixes please include tests that can catch regressions
- [ ] All acceptance test scenarios included in the PR which verifies a bugfix or a requested feature reported by a non-member are tagged with `@external-feedback` tag.
- [ ] Follows the [commit message standard](https://github.com/redhat-developer/service-binding-operator/blob/master/CONTRIBUTING.md#commits)

### CODE REVIEW

**Comment by pmacik** [comment]
@shruthihub is not part of @redhat-developer organization. I already asked @jasperchui to invite her.

**Comment by sadlerap** [comment]
Got it; once she's invited, this should be good to go, right?

**Review by baijum — APPROVED** [review]

**Pull request merged**
