### PR TITLE
make leader-with-lease as an option of deployment

### PR DESCRIPTION
**Pull request by cdlliuy**
### Motivation

 Per issue https://github.com/redhat-developer/service-binding-operator/issues/488 
### Changes
Make changes per 
https://github.com/operator-framework/operator-sdk/blob/c93321571d8300bb1f60f548de12e83f05d2d267/doc/user-guide.md#leader-for-life
https://github.com/operator-framework/operator-sdk/blob/c93321571d8300bb1f60f548de12e83f05d2d267/doc/user-guide.md#leader-with-lease

No change in deployment yaml , so by default the `leader-for-life` will be used. 
`leader-with-lease` is enabled only when the environment variable SERVICE_BINDING_OPERATOR_LEADER_ELECTION_OPTION is set to `leader-with-lease` explicitly 

### Testing

There is no main_test.go ..  So I didn't add test case for this yet. 

For further more details refer the CONTRIBUTING.md

### CODE REVIEW

**Comment by Avni-Sharma** [comment]
I am receiving an error when I set the env var,
```
2020-06-05T11:28:16.488+0530	ERROR	main	Error on creating a new manager instance	{"error": "unable to find leader election namespace: not running in-cluster, please specify LeaderElectionNamespace"}
```

When the env var isn't set, the operator works

**Comment by cdlliuy** [comment]
@Avni-Sharma  
According to the document https://docs.openshift.com/container-platform/4.4/operators/operator_sdk/osdk-leader-election.html
```
When the Operator is not running in a cluster, the Manager returns an error when starting since it cannot detect the Operator’s namespace in order to create the ConfigMap for leader election. You can override this namespace by setting the Manager’s LeaderElectionNamespace option.
```

I think you are not running the operator in a cluster. 

To fix this,  I added  another env `SERVICE_BINDING_OPERATOR_LEADER_ELECTION_NAMESPACE` to allow the explicitly claim of LeaderElectionNamespace.  If LeaderElectionNamespace is not defined or equals to "",   the in cluster namespace will be used per https://github.com/kubernetes-sigs/controller-runtime/blob/master/pkg/leaderelection/leader_election.go#L62

**Comment by Avni-Sharma** [comment]
leader election successfully works:
a success scenario - 
```
I0611 22:39:17.857681   24479 leaderelection.go:241] attempting to acquire leader lease  default/service-binding-operator...
2020-06-11T22:39:17.857+0530	INFO	controller-runtime.manager	starting metrics server	{"path": "/metrics"}
I0611 22:39:18.439499   24479 leaderelection.go:251] successfully acquired lease default/service-binding-operator
```

A failure scenario- (Giving a wrong namespace)
```
E0611 22:46:22.563675   27754 leaderelection.go:334] error initially creating leader election record: namespaces "hjhjh" not found
E0611 22:46:26.792381   27754 leaderelection.go:334] error initially creating leader election record: namespaces "hjhjh" not found
E0611 22:46:30.490116   27754 leaderelection.go:334] error initially creating leader election record: namespaces "hjhjh" not found
E0611 22:46:34.138498   27754 leaderelection.go:334] error initially creating leader election record: namespaces "hjhjh" not found
```

**Pull request merged**
