### PR TITLE
Add java app sample

### PR DESCRIPTION
**Pull request by ldimaggi**
This sample will also demonstrate custom env variables.

### CODE REVIEW

**Comment by pmacik** [comment]
This depends on https://github.com/redhat-developer/service-binding-operator/pull/159

**Comment by otaviof** [comment]
Could we use something shorter? The directory name is `bind_imported_java_app_to_incluster_operator_managed_PostgreSQL_db`, where we could be using something like `java_postgresql`.

**Comment by sbose78** [comment]
> Could we use something shorter? The directory name is bind_imported_java_app_to_incluster_operator_managed_PostgreSQL_db, where we could be using something like java_postgresql

@ldimaggi ,
Or maybe just remove the "bind_imported_" sub string since it is obvious and repetitive.

**Comment by pmacik** [comment]
> Could we use something shorter? The directory name is `bind_imported_java_app_to_incluster_operator_managed_PostgreSQL_db`, where we could be using something like `java_postgresql`.

Yes, but let's do it in another PR ;)

**Pull request merged**
