### PR TITLE
fix: fill in Reason field when updating the ServiceBinding's status (…

### LINKED ISSUE #909: Swallowed Error
Currently, when referencing a service that does not exist in my service binding I get the following error:
```
{"level":"error","ts":1615816703.4740953,"logger":"reconciler","msg":"Failed to update SBR conditions","Request.Namespace":"camel-k","Request.Name":"sample","ServiceBinding.Name":"sample","sbr":{"apiVersion":"binding.operators.coreos.com/v1alpha1","kind":"ServiceBinding","namespace":"camel-k","name":"sample"},"error":"ServiceBinding.binding.operators.coreos.com \"sample\" is invalid: status.conditions.reason: Invalid value: \"\": status.conditions.reason in body should be at least 1 chars long"
```

which swallows the real error (the service doesn't exist).

### PR DESCRIPTION
**Pull request by johnpoth**
…#909)

### Motivation

fixes #909 

Thanks !

### CODE REVIEW

**Comment by pedjak** [comment]
@johnpoth  is the issue still valid after #919 is merged?

**Comment by johnpoth** [comment]
@pedjak will try to reproduce with the latest changes. Should I wait for a v0.7.0 release ? Thanks !

**Comment by pedjak** [comment]
@johnpoth 0.7.0 just got released. Please check.

**Comment by johnpoth** [comment]
Fixed with v0.7.1, thanks !

**Pull request closed without merging**
