### PR TITLE
Adding new API for mapping environment parameters

### PR DESCRIPTION
**Pull request by Avni-Sharma**
Refer- https://jira.coreos.com/browse/ODC-1422

Add API for envVar as stated in the following CR

```
apiVersion: apps.openshift.io/v1alpha1
kind: ServiceBindingRequest
metadata:
  name: binding-request
  namespace: openshift-operators
spec:
  applicationSelector:
    matchLabels:
      connects-to: db-demo
      environment: demo
    resourceKind: DeploymentConfig
  backingSelector:
    resourceRef: db-demo
    resourceKind: databases.postgresql.baiju.dev
    resourceVersion: v1alpha1
  
  envVar:
  - Name: JDBC_CONNECTION_STRING
    Value: ${status.dbCredentials.user}:${status.dbCredentials.password}@${status.dbConnectionIP} 
```

### CODE REVIEW

**Comment by DhritiShikhar** [comment]
@Avni-Sharma Can you add tests for the same?

**Comment by sbose78** [comment]
Do you wish to use this branch to commit the controller as well, @Avni-Sharma  ?

**Comment by DhritiShikhar** [comment]
@sbose78 As per my understanding, @Avni-Sharma was about to raise another PR for controller related changes. The `e2e` tests are failing for this PR though which is why we didn't merge this one.

**Comment by sbose78** [comment]
Thanks @DhritiShikhar .
@Avni-Sharma , you would need these changes anyway. You could keep it simple by pushing your changes to this branch itself.

**Comment by Avni-Sharma** [comment]
Closing this as a new implementation is being carried in #159

**Pull request closed without merging**
