### PR TITLE
Upgrade operator-sdk to 0.15.1

### PR DESCRIPTION
**Pull request by sbose78**
### Motivation

- Upgrade operator-sdk to 0.15.1
Steps:
- `brew upgrade operator-sdk` ( for mac )
- `operator-sdk print-deps` gives the required changes
```
require (
        github.com/operator-framework/operator-sdk v0.15.1
        sigs.k8s.io/controller-runtime v0.4.0
)

// Pinned to kubernetes-1.16.2
replace (
        k8s.io/api => k8s.io/api v0.0.0-20191016110408-35e52d86657a
        k8s.io/apiextensions-apiserver => k8s.io/apiextensions-apiserver v0.0.0-20191016113550-5357c4baaf65
        k8s.io/apimachinery => k8s.io/apimachinery v0.0.0-20191004115801-a2eda9f80ab8
        k8s.io/apiserver => k8s.io/apiserver v0.0.0-20191016112112-5190913f932d
        k8s.io/cli-runtime => k8s.io/cli-runtime v0.0.0-20191016114015-74ad18325ed5
        k8s.io/client-go => k8s.io/client-go v0.0.0-20191016111102-bec269661e48
        k8s.io/cloud-provider => k8s.io/cloud-provider v0.0.0-20191016115326-20453efc2458
        k8s.io/cluster-bootstrap => k8s.io/cluster-bootstrap v0.0.0-20191016115129-c07a134afb42
        k8s.io/code-generator => k8s.io/code-generator v0.0.0-20191004115455-8e001e5d1894
        k8s.io/component-base => k8s.io/component-base v0.0.0-20191016111319-039242c015a9
        k8s.io/cri-api => k8s.io/cri-api v0.0.0-20190828162817-608eb1dad4ac
        k8s.io/csi-translation-lib => k8s.io/csi-translation-lib v0.0.0-20191016115521-756ffa5af0bd
        k8s.io/kube-aggregator => k8s.io/kube-aggregator v0.0.0-20191016112429-9587704a8ad4
        k8s.io/kube-controller-manager => k8s.io/kube-controller-manager v0.0.0-20191016114939-2b2b218dc1df
        k8s.io/kube-proxy => k8s.io/kube-proxy v0.0.0-20191016114407-2e83b6f20229
        k8s.io/kube-scheduler => k8s.io/kube-scheduler v0.0.0-20191016114748-65049c67a58b
        k8s.io/kubectl => k8s.io/kubectl v0.0.0-20191016120415-2ed914427d51
        k8s.io/kubelet => k8s.io/kubelet v0.0.0-20191016114556-7841ed97f1b2
        k8s.io/legacy-cloud-providers => k8s.io/legacy-cloud-providers v0.0.0-20191016115753-cf0698c3a16b
        k8s.io/metrics => k8s.io/metrics v0.0.0-20191016113814-3b1a734dba6e
        k8s.io/sample-apiserver => k8s.io/sample-apiserver v0.0.0-20191016112829-06bb3c9d77c9
)

replace github.com/docker/docker => github.com/moby/moby v0.7.3-0.20190826074503-38ab9da00309 // Required by Helm
replace github.com/openshift/api => github.com/openshift/api v0.0.0-20190924102528-32369d4db2ad // Required until https://github.com/operator-framework/operator-lifecycle-manager/pull/1241 is resolved
```
- `rm -rf vendor` ( probably not needed )
- `go mod tidy`.. ouch  https://github.com/kubernetes/client-go/issues/628
- `go mod tidy` again.
- `go mod vendor`
- `make build`

### Changes

- Upgrade operator-sdk to 0.15.1
- pin github.com/Azure/go-autorest => github.com/Azure/go-autorest v12.2.0+incompatible because of https://github.com/kubernetes/client-go/issues/628

### Testing
Successful compilation should be good enough.

### CODE REVIEW

**Comment by pedjak** [comment]
@sbose78 this PR removes `.travis.yaml`. How we are going to push operator on merge to master now?

**Comment by baijum** [comment]
> @sbose78 this PR removes `.travis.yaml`. How we are going to push operator on merge to master now?

Looks like the top-level `.travis.yaml` is still there.

**Comment by pedjak** [comment]
@baijum yes, my bad, but in that case we need to update the following line as well:

https://github.com/redhat-developer/service-binding-operator/blob/master/.travis.yml#L14 

and Makefile, since since CSV are generated now using `operator-sdk generate csv` command.

**Comment by sbose78** [comment]
Few other changes to be noted:

- update sdk version in travis config 71f7d87 @Avni-Sharma  please review.
- 6377e1d9e2e678f9521a127f3709c3e9dc55abc0 adapt replacement of "operator-sdk up" command
- fbbd34fb5dd9700edea4e4ce80fe9d039109c4e8 changes to main.go to handle deprecation issue caught by `make lint`
```
make lint
python3 -m venv /Users/sbose/appbinding/src/github.com/redhat-developer/service-binding-operator/out/venv3
/Users/sbose/appbinding/src/github.com/redhat-developer/service-binding-operator/out/venv3/bin/pip install --upgrade setuptools
Collecting setuptools
  Downloading https://files.pythonhosted.org/packages/a7/c5/6c1acea1b4ea88b86b03280f3fde1efa04fefecd4e7d2af13e602661cde4/setuptools-45.1.0-py3-none-any.whl (583kB)
    100% |████████████████████████████████| 593kB 3.3MB/s 
Installing collected packages: setuptools
  Found existing installation: setuptools 40.8.0
    Uninstalling setuptools-40.8.0:
      Successfully uninstalled setuptools-40.8.0
Successfully installed setuptools-45.1.0
You are using pip version 19.0.3, however version 20.0.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
/Users/sbose/appbinding/src/github.com/redhat-developer/service-binding-operator/out/venv3/bin/pip install --upgrade pip
Collecting pip
  Downloading https://files.pythonhosted.org/packages/54/0c/d01aa759fdc501a58f431eb594a17495f15b88da142ce14b5845662c13f3/pip-20.0.2-py2.py3-none-any.whl (1.4MB)
    100% |████████████████████████████████| 1.4MB 15.3MB/s 
Installing collected packages: pip
  Found existing installation: pip 19.0.3
    Uninstalling pip-19.0.3:
      Successfully uninstalled pip-19.0.3
Successfully installed pip-20.0.2
curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b ./out v1.18.0
golangci/golangci-lint info checking GitHub for tag 'v1.18.0'
golangci/golangci-lint info found version: 1.18.0 for v1.18.0/darwin/amd64
golangci/golangci-lint info installed ./out/golangci-lint
# This is required for OpenShift CI enviroment
# Ref: https://github.com/openshift/release/pull/3438#issuecomment-482053250
GOCACHE="/Users/sbose/appbinding/src/github.com/redhat-developer/service-binding-operator/out/gocache" /Users/sbose/appbinding/src/github.com/redhat-developer/service-binding-operator/out/golangci-lint  run --deadline=30m
cmd/manager/main.go:101:23: SA1019: restmapper.NewDynamicRESTMapper is deprecated: NewDynamicRESTMapper exists for historical compatibility and should not be used. See that it was implemented in the controller-runtime. More info: https://github.com/kubernetes-sigs/controller-runtime/pull/554  (staticcheck)
                MapperProvider:     restmapper.NewDynamicRESTMapper,
```

**Comment by baijum** [comment]
> and Makefile, since since CSV are generated now using `operator-sdk generate csv` command.

Good catch @pedjak !

@sbose78 Please make this change in Makefile also. Then we can merge this PR.

**Comment by sbose78** [comment]
Done 71c890b , good catch!

**Pull request merged**
