### PR TITLE
Reverting Trigger Rebinding

### PR DESCRIPTION
**Pull request by otaviof**
Removing logic to update `ServiceBindingRequest` objects during reconciliation. The `spec` of a given resource should always belong to the user, not subject for operator driven changes.

Forceful trigger-rebinding changes were added on PR #134 and reverted here.

### Current Alternative

The operator respects `metadata.generation`, so if generation is incremented, the operator will reconcile that object. Please notice the predicate action employed in `controller.go`:

```go
pred := predicate.Funcs{
	UpdateFunc: func(e event.UpdateEvent) bool {
		// ignore updates to CR status in which case metadata.Generation does not change
		return e.MetaOld.GetGeneration() != e.MetaNew.GetGeneration()
	},
}
```

You can see where the operator takes the decision.

### CODE REVIEW

**Comment by otaviof** [comment]
> Curious, why do you think this is an operator driven change? This **is** for the user to trigger an update by setting `triggerBinding : true`

It might have been written for the user, but the operator needs to `update` the object to avoid a infinite loop when this flag was set.
 
The primary reasoning behind this change is to use default tooling in Kubernetes instead of cooking our own.

**Comment by sbose78** [comment]
> but the operator needs to update the object to avoid a infinite loop when this flag was set.

Agreed.

> use default tooling in Kubernetes 

What could a user use to trigger rebinding?

**Comment by isutton** [comment]
Wouldn’t bumping `metadata.generation` suffice?

Another option would be using an annotation if being explicit is a requirement.

**Comment by sbose78** [comment]
:) The API server doesn't let the user bump the generation. I tried - it's just sets it back to the old one.

**Comment by otaviof** [comment]
> :) The API server doesn't let the user bump the generation. I tried - it's just sets it back to the old one.

Indeed, I have just tested this scenario, and updating generation of a CRD is not allowed for the time being. For instance: https://github.com/kubernetes/kubernetes/issues/58778

**Comment by otaviof** [comment]
Therefore, I'm going to pursue the annotations path, sounds like second best option in this story.

**Comment by sbose78** [comment]
> Therefore, I'm going to pursue the annotations path, sounds like second best option in this story.

Sure. Could you describe a bit how that would look ?

**Comment by otaviof** [comment]
> What could a user use to trigger rebinding?

That would come from the user editing a given resource that is under watch by this operator. The use case of "forcing rebinding" also implies the operator is not watching all the resources that it should, and since #162 is fixing this, we should take that route IMHO.

**Comment by otaviof** [comment]
> Sure. Could you describe a bit how that would look ?

We are already managing annotations to identify which rebinding instance a given resource under watch belongs to. The same principle could be applied to add one more flag to trigger a forceful rebinding, and then, since the operator would update annotations at the end of the process anyways, that would be removed as well.

**Comment by sbose78** [comment]
> The same principle could be applied to add one more flag to trigger a forceful rebinding

If I were to add an annotation to a ServiceBindingRequest CR, I don't think that would trigger an event.

**Comment by otaviof** [comment]
> > The same principle could be applied to add one more flag to trigger a forceful rebinding
> 
> If I were to add an annotation to a ServiceBindingRequest CR, I don't think that would trigger an event.

Just tested it, and it does create an event. So, we could manage annotations for this use-case.

However, the best approach here would not need to force any reconciliation, but to watch resources that would trigger this instead. :-)

**Comment by sbose78** [comment]
> Just tested it, and it does create an event.

You mean, adding an annotation triggered a reconcile?

**Comment by otaviof** [comment]
> > Just tested it, and it does create an event.
> 
> You mean, adding an annotation triggered a reconcile?

Yep, it does trigger a reconcile. However, intentionally I added a `return true` on the predicate, since I knew the `metadata.generation` would still be the same, despite of different annotations.

**Comment by sbose78** [comment]
> Yep, it does trigger a reconcile. 

great.

> However, intentionally I added a return true on the predicate

right, else the event wouldn't trickle in. 

OK, I'm convinced there's the annotations path in future if we need to! 🍾

**Pull request merged**
