### PR TITLE
Allow ServiceBindingSpec.Application to be null (#731)

### PR DESCRIPTION
**Pull request by johnpoth**
### Motivation

<< Why this change is relevant, what's the "story" behind it? >>
#731
### Changes

<< What has been changed in order to achieve "story's" objective? >>

Append `omitempty `

### Testing

<< How to test those changes, reference implementation of unit/acceptance tests. >>

For further more details refer the CONTRIBUTING.md

### CODE REVIEW

**Comment by baijum** [comment]
Thanks @johnpoth !

Please generate the openapi code:
Just now I send a PR to fix a path issue: #733
You can follow the instruction given in the description of that PR.

**Comment by johnpoth** [comment]
Thanks @baijum ! I was missing the `export GO_PACKAGE_ORG_NAME=redhat-developer`, I've ran the commands suggested and updated the PR

**Pull request merged**
