### PR TITLE
[WIP] Add support for custom environment variables mapping

### PR DESCRIPTION
**Pull request by Avni-Sharma**
A [WIP]. Open for feedback and discussions.
Refers - https://jira.coreos.com/browse/APPSVC-39

```
statusDescriptors:
  description: Name of the Secret to hold the DB user and password
    displayName: DB Password Credentials
    path: dbCredentials
    x-descriptors:
      - urn:alm:descriptor:io.kubernetes:Secret
      - urn:alm:descriptor:servicebindingrequest:env:object:secret:user
      - urn:alm:descriptor:servicebindingrequest:env:object:secret:password
  description: Database connection IP address
    displayName: DB IP address
    path: dbConnectionIP
    x-descriptors:
      - urn:alm:descriptor:servicebindingrequest:env:attribute
```
```
apiVersion: apps.openshift.io/v1alpha1
kind: ServiceBindingRequest
metadata:
  name: binding-request
  namespace: openshift-operators
spec:
  applicationSelector:
    matchLabels:
      connects-to: db-demo
      environment: demo
    resourceKind: DeploymentConfig
  backingSelector:
    resourceRef: db-demo
    resourceKind: databases.postgresql.baiju.dev
    resourceVersion: v1alpha1
  
  envVar:
  - Name: JDBC_CONNECTION_STRING
    Value: ${status.dbCredentials.user}:${status.dbCredentials.password}@${status.dbConnectionIP} 
```

### CODE REVIEW

**Comment by ron1** [comment]
Am I correct that the above annotated OLM CSV causes the service-binding-operator to generate an intermediate Secret with three keys named user, password, and dbConnectionIP? If so, 
why complicate the mapping by duplicating the logic already captured in the OLM annotations? Instead, consider using the OLM-annotation-based intermediate Secret generated by the operator as the mapping source and simply reference the intermediate Secret keys by name. This change would result in the simplified mapping below with no paths needed:

```
  envVar:
  - Name: JDBC_CONNECTION_STRING
    Value: ${user}:${password}@${dbConnectionIP}
```

**Comment by sbose78** [comment]
@ron1 

> Am I correct that the above annotated OLM CSV causes the service-binding-operator to generate an intermediate Secret with three keys named user, password, and dbConnectionIP?

Nope!


+ @Avni-Sharma @akashshinde 

JDBC_CONNECTION_STRING would be a key in the intermediate secret and it's value would be whatever is resolved from `${status.dbCredentials.user}:${status.dbCredentials.password}@${status.dbConnectionIP}`

**Comment by ron1** [comment]
From my perspective, the intermediate secret is the contract and single source of truth for the application object. Any expressions used directly by the application object should reference the intermediate secret.

**Comment by Avni-Sharma** [comment]
Closing this as a new implementation is being carried in https://github.com/redhat-developer/service-binding-operator/pull/159

**Pull request closed without merging**
