### PR TITLE
Add example for using the Service Binding Operator with the IBM Cloud Operator

### PR DESCRIPTION
**Pull request by pdettori**
### Motivation

Add example for using the Service Binding Operator with an out-of-cluster service managed by the IBM Cloud Operator

### Changes

Documentation and yaml templates for the example have been added to the examples directory. 

### Testing

No code has been changed since this is just documenting an example of usage, so no new e2e tests have been added.

For further more details refer the CONTRIBUTING.md

### CODE REVIEW

**Comment by sbose78** [comment]
Thanks a lot, we'll fix https://github.com/redhat-developer/service-binding-operator/issues/354 and then have this tested

**Comment by pdettori** [comment]
> Thanks a lot, we'll fix #354 and then have this tested

Thanks @sbose78, yes, we'll need that fixed and will also need to update the custom env vars with the new syntax.

**Comment by pdettori** [comment]
@sbose78 I opened #358 to track a blocking issue that is preventing me from retesting the scenario.

**Comment by sbose78** [comment]
I'll make a PR to your branch with the updated syntax, Paolo.

**Comment by sbose78** [comment]
https://github.com/redhat-developer/service-binding-operator/pull/360
fix is merged, existing syntax is intact with `backingServiceSelectors`, could you validate this and let me know?

**Comment by pdettori** [comment]
@sbose78 I just finished testing using an image built from master. It works ! However I had to do some workaround to make it work for my OLM installed operator. First, I had to install it in a single namespace, second, I updated the image in csv and deployment to use the image I built from master, third, I had to do some hacking of roles - see https://github.com/redhat-developer/service-binding-operator/issues/358

**Comment by sbose78** [comment]
Nice!

The easiest way would be to run "make local" to test master.

**Comment by pdettori** [comment]
> The easiest way would be to run "make local" to test master.
@sbose78 good point ! I just wanted to test if #358 was still there using the master build. It seems now it might be related to the specifics of the RBAC rules for the OLM install.

**Comment by sbose78** [comment]
Ah, missed updating the README https://github.com/redhat-developer/service-binding-operator#example-scenarios

**Pull request merged**
