### PR TITLE
Split BindingReady into CollectionReady and InjectionReady

### LINKED ISSUE #381: Generic binding : BindingFail status is reported
Even though the binding secret gets created fine, the status is marked as `BindingFail`

```
apiVersion: apps.openshift.io/v1alpha1
kind: ServiceBindingRequest
metadata:
  creationTimestamp: '2020-03-12T21:05:44Z'
  generation: 1
  name: node-todo-git
  namespace: sbose
  resourceVersion: '221728'
  selfLink: >-
    /apis/apps.openshift.io/v1alpha1/namespaces/sbosse/servicebindingrequests/node-todo-git
  uid: 3413f95b-7cd6-44b7-9a62-daaec834be18
spec:
  backingServiceSelectors:
    - group: etcd.database.coreos.com
      kind: EtcdCluster
      resourceRef: example
      version: v1beta2
  detectBindingResources: true
status:
  bindingStatus: BindingFail
  conditions:
    - lastHeartbeatTime: '2020-03-12T21:05:59Z'
      lastTransitionTime: '2020-03-12T21:05:45Z'
      message: application ResourceRef or MatchLabel not found
      reason: BindingFail
      status: 'False'
      type: Ready
  secret: node-todo-git
```

### PR DESCRIPTION
**Pull request by DhritiShikhar**
### Motivation

To fix  #381 

### Changes

Splits the `BindingReady` type into more specific types:
- CollectionReady which would be related to the collection and persistence of intermediate manifests (secrets, config maps, etc)
- InjectionReady which would be related to change the applications' manifests to use those intermediate manifests:

### How to test

1. Follow the steps given in this [example](https://github.com/redhat-developer/service-binding-operator/tree/master/examples/nodejs_postgresql) to:
- install DB operator, Service Binding Operator
- Import an application
- Create a DB instance 

2. Create the following `ServiceBindingRequest`:

```
apiVersion: apps.openshift.io/v1alpha1
kind: ServiceBindingRequest
metadata:
  name: binding-request
  namespace: service-binding-demo
spec:
 backingServiceSelector:
    group: postgresql.baiju.dev
    version: v1alpha1
    kind: Database
    resourceRef: db-demo
```

3. Use the following command to check if the status has been updated:
`oc get ServiceBindingRequest binding-request -o yaml`

The output should have `status.conditions.type` as 
- `CollectionReady` with `status: "True"`
-  `InjectionReady` with `status: "False"`

```
status:
  conditions:
  - lastHeartbeatTime: 2020-04-23T06:25:16Z
    lastTransitionTime: 2020-04-23T06:25:16Z
    message: application ResourceRef or MatchLabel not found
    reason: EmptyApplicationSelector
    status: "True"
    type: CollectionReady
  - lastHeartbeatTime: 2020-04-23T06:25:16Z
    lastTransitionTime: 2020-04-23T06:25:16Z
    message: application ResourceRef or MatchLabel not found
    reason: EmptyApplicationSelector
    status: "False"
    type: InjectionReady
```

## Demo

https://youtu.be/NI6Fd5l65rw

### CODE REVIEW

**Comment by cdlliuy** [comment]
@DhritiShikhar  @isutton @sbose78 ,  with the changes above,  I found our previous CLI experience broken since the status.condition.ready is not there anymore. 

First of all,  I am quite supporting this changes since splitting to different phase will help to manage the CR status and debug issues. 
But from UX perspective,   I hope we can keep a stable `ready` condition there as the overall ready status.  i.e. when `injectReady=true`, then set `ready=true` as well.  Then, UX side can always depend on the `ready`, and no need to consider different phases at all.   

Comments?

**Comment by isutton** [comment]
Let's start with a rough review of the actual chain of events:

1. Binding data is collected from declared services and related resources.
2. Collected binding data is projected into the related Secret resource; if this operation is successful, `CollectionReady` is set to `True` indicating the secret is ready to be used.
3. The secret is injected into the declared application resources and if all application resources have been properly updated, `InjectionReady` is set to `True`. Please note this only happens if `CollectionReady` is set to `True`.

Given that, perhaps `Ready` condition should be set to `True` when `CollectionReady` is `True` and either `InjectionReady` is also `True` or no application has been declared in the SBR although I don't know if this will make it more confusing to the end user than depending on the more fine-grained conditions in this particular case.

Could also clarify what are the expectations of your CLI experience?

**Comment by cdlliuy** [comment]
@isutton ,  Since `InjectionReady` is set to `True` only happens if `CollectionReady` is set to `True`,  then we can assume to set `Ready` always equal to `InjectionReady`. 

For our CLI experience,  we will list whether a sbr is ready to end-user.   So, previously,  the cli implementation is seeking for "status.conditions[].type==Ready", then check its `status`.  Then, with this PR,  we need to update to check "type=InjectionReady" .   

I am worried that the condition name will be changed someday later ...  So,  I suggest to have a duplicated entry just equal the latest condition (injectionReady in current workflow),  so that the cli implementation can stay stable .. 

For example, in below format: 
```
status:
  conditions:
  - lastHeartbeatTime: "2020-08-31T08:53:34Z"
    lastTransitionTime: "2020-08-31T07:20:49Z"
    status: "True"
    type: Ready
  - lastHeartbeatTime: "2020-08-31T08:53:34Z"
    lastTransitionTime: "2020-08-31T07:20:49Z"
    status: "True"
    type: CollectionReady
  - lastHeartbeatTime: "2020-08-31T08:53:34Z"
    lastTransitionTime: "2020-08-31T07:20:49Z"
    status: "True"
    type: InjectionReady
```

**Comment by DhritiShikhar** [comment]
@cdlliuy @isutton 

I would like to re-think and discuss the condition type names "CollectionReady", "InjectionReady" **as well as** "Ready".
But until we come to a conclusion, we should go ahead with a duplicate final entry "Ready" as a temporary solution.

**Comment by cdlliuy** [comment]
@DhritiShikhar ,  will you help to raise a PR as early as possible?   or we can raise a PR for this?   We are in the middle to harvest the latest master, and would like to get the temporary solution ready before the `breaking api changes` in #608  is merged.

**Comment by DhritiShikhar** [comment]
@cdlliuy 

You can raise a PR for it. I will provide a quick review to it as well as contribute to it.

**Comment by DhritiShikhar** [comment]
Sharing the screenshot here as well @cdlliuy 

Screenshot from 2020-09-03 17-10-01

**Comment by Avni-Sharma** [comment]
> @DhritiShikhar @isutton @sbose78 , with the changes above, I found our previous CLI experience broken since the status.condition.ready is not there anymore.
> 
> First of all, I am quite supporting this changes since splitting to different phase will help to manage the CR status and debug issues.
> But from UX perspective, I hope we can keep a stable `ready` condition there as the overall ready status. i.e. when `injectReady=true`, then set `ready=true` as well. Then, UX side can always depend on the `ready`, and no need to consider different phases at all.
> 
> Comments?

According to this, UX can depend on InjectReady itself, :thinking:

**Pull request merged**
