### PR TITLE
bump version to v1.3.2 for helm chart

### PR DESCRIPTION
**Pull request by sadlerap**
Signed-off-by: Andy Sadler <ansadler@redhat.com>

# Changes

Bumps the version in our help chart manifest to v1.3.2.

# Submitter Checklist

As the author of this PR, please check off the items in this checklist:

- [ ] [Docs](https://github.com/redhat-developer/service-binding-operator/blob/master/CONTRIBUTING.md#docs) 
  included if any changes are user facing
- [ ] [Tests](https://github.com/redhat-developer/service-binding-operator/blob/master/CONTRIBUTING.md#tests)
  included if any functionality added or changed. For bugfixes please include tests that can catch regressions
- [ ] All acceptance test scenarios included in the PR which verifies a bugfix or a requested feature reported by a non-member are tagged with `@external-feedback` tag.
- [ ] Follows the [commit message standard](https://github.com/redhat-developer/service-binding-operator/blob/master/CONTRIBUTING.md#commits)

### CODE REVIEW

**Comment by pmacik** [comment]
@sadlerap The `acceptance-tests-skipped` is only an indicator whether the acceptance tests were skipped or not by the CI, the acceptance tests won't execute if you unset-it.

Additionally, you PR only changes the chart which does not fall under any of the following list:
* SBO release
* images or operator manifests
* the acceptance testing framework
* the related CI 

Anything related to the chart or the chart itself is not covered in acceptance tests, at all. So the execution of the acceptance tests was skipped (and marked as such) correctly.

**Comment by sadlerap** [comment]
hmm, not sure why it says I unset `acceptance-tests-skipped`; I certainly didn't intend to do that.

**Review by pmacik — APPROVED** [review]
/approve
/lgtm

**Pull request merged**
