### PR TITLE
Update operator-sdk verion to 0.17.0

### PR DESCRIPTION
**Pull request by baijum**
### Motivation

Fixes: #449

It's a good practice to upgrade dependencies on a regular basis.

### Changes

Updated version.

### Testing

For further more details refer the CONTRIBUTING.md

### CODE REVIEW

**Comment by sbose78** [comment]
Thank you @baijum ,  could you please add more details as to what you've done such as https://github.com/redhat-developer/service-binding-operator/pull/317

**Comment by baijum** [comment]
To reduce the size of this PR and since OLM is not tightly coupled with SDK, I am separating upgrade of OLM into another PR: https://github.com/redhat-developer/service-binding-operator/pull/474

**Comment by baijum** [comment]
There are some dependency issues when upgrading. For now, I am closing this PR. There is another PR ( #478 ) to upgrade to 0.16.0 version of Operator SDK.

**Pull request closed without merging**
