### PR TITLE
fixes `make local` CLI

### LINKED ISSUE #483: `make local` fails on master
Failure in running operator locally through `make local` CLI

```
➜  service-binding-operator git:(master) make clean; make local        
rm -rf  /home/dhritishikhar/go/src/github.com/redhat-developer/service-binding-operator/out
kubectl delete -f deploy/crds/apps_v1alpha1_servicebindingrequest_cr.yaml
Error from server (NotFound): error when deleting "deploy/crds/apps_v1alpha1_servicebindingrequest_cr.yaml": servicebindingrequests.apps.openshift.io "example-servicebindingrequest" not found
make: [Makefile:366: deploy-clean] Error 1 (ignored)
kubectl delete -f deploy/crds/apps.openshift.io_servicebindingrequests_crd.yaml
customresourcedefinition.apiextensions.k8s.io "servicebindingrequests.apps.openshift.io" deleted
kubectl delete -f deploy/operator.yaml
Error from server (NotFound): error when deleting "deploy/operator.yaml": deployments.apps "service-binding-operator" not found
make: [Makefile:368: deploy-clean] Error 1 (ignored)
kubectl delete -f deploy/role_binding.yaml
rolebinding.rbac.authorization.k8s.io "service-binding-operator" deleted
kubectl delete -f deploy/role.yaml
role.rbac.authorization.k8s.io "service-binding-operator" deleted
kubectl delete -f deploy/service_account.yaml
serviceaccount "service-binding-operator" deleted
kubectl create -f deploy/service_account.yaml
serviceaccount/service-binding-operator created
kubectl create -f deploy/role.yaml
role.rbac.authorization.k8s.io/service-binding-operator created
kubectl create -f deploy/role_binding.yaml
rolebinding.rbac.authorization.k8s.io/service-binding-operator created
kubectl apply -f deploy/crds/apps.openshift.io_servicebindingrequests_crd.yaml
customresourcedefinition.apiextensions.k8s.io/servicebindingrequests.apps.openshift.io created
operator-sdk --verbose run --local --operator-flags "--zap-level=debug --zap-encoder=console "
DEBU[0000] Debug logging is set                         
INFO[0000] Running the operator locally in namespace default. 
DEBU[0000] Running []string{"go", "build", "-o", "build/_output/bin/service-binding-operator-local", "-mod=vendor", "github.com/redhat-developer/service-binding-operator/cmd/manager"} 
go: inconsistent vendoring in /home/dhritishikhar/go/src/github.com/redhat-developer/service-binding-operator:
	cloud.google.com/go@v0.45.1: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	github.com/coreos/etcd-operator@v0.9.4: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	github.com/go-logr/logr@v0.1.0: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	github.com/go-openapi/spec@v0.19.4: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	github.com/google/go-containerregistry@v0.0.0-20191218175032-34fb8ff33bed: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	github.com/imdario/mergo@v0.3.8: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	github.com/openshift/api@v3.9.1-0.20190924102528-32369d4db2ad+incompatible: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	github.com/openshift/custom-resource-status@v0.0.0-20190822192428-e62f2f3b79f3: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	github.com/operator-backing-service-samples/postgresql-operator@v0.0.0-20191023140509-5c3697ed3069: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	github.com/operator-framework/operator-lifecycle-manager@v0.0.0-20200130164400-12c06cfc05c4: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	github.com/operator-framework/operator-sdk@v0.15.2: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	github.com/spf13/pflag@v1.0.5: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	github.com/stretchr/testify@v1.4.0: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	gotest.tools@v2.2.0+incompatible: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	k8s.io/api@v0.17.1: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	k8s.io/apiextensions-apiserver@v0.17.1: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	k8s.io/apimachinery@v0.17.1: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	k8s.io/client-go@v12.0.0+incompatible: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	k8s.io/code-generator@v0.0.0: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	k8s.io/gengo@v0.0.0-20191010091904-7fa3014cb28f: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	k8s.io/kube-openapi@v0.0.0-20190918143330-0270cf2f1c1d: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	knative.dev/pkg@v0.0.0-20191221032535-9fda5bd59a67: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	knative.dev/serving@v0.9.0: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	sigs.k8s.io/controller-runtime@v0.4.0: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	sigs.k8s.io/controller-tools@v0.2.4: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	github.com/Azure/go-autorest: is replaced in go.mod, but not marked as replaced in vendor/modules.txt
	github.com/docker/docker: is replaced in go.mod, but not marked as replaced in vendor/modules.txt
	github.com/openshift/api: is replaced in go.mod, but not marked as replaced in vendor/modules.txt
	github.com/openshift/client-go: is replaced in go.mod, but not marked as replaced in vendor/modules.txt
	github.com/prometheus/client_golang: is replaced in go.mod, but not marked as replaced in vendor/modules.txt
	helm.sh/helm/v3: is replaced in go.mod, but not marked as replaced in vendor/modules.txt
	k8s.io/api: is replaced in go.mod, but not marked as replaced in vendor/modules.txt
	k8s.io/apiextensions-apiserver: is replaced in go.mod, but not marked as replaced in vendor/modules.txt
	k8s.io/apimachinery: is replaced in go.mod, but not marked as replaced in vendor/modules.txt
	k8s.io/apiserver: is replaced in go.mod, but not marked as replaced in vendor/modules.txt
	k8s.io/cli-runtime: is replaced in go.mod, but not marked as replaced in vendor/modules.txt
	k8s.io/client-go: is replaced in go.mod, but not marked as replaced in vendor/modules.txt
	k8s.io/cloud-provider: is replaced in go.mod, but not marked as replaced in vendor/modules.txt
	k8s.io/cluster-bootstrap: is replaced in go.mod, but not marked as replaced in vendor/modules.txt
	k8s.io/code-generator: is replaced in go.mod, but not marked as replaced in vendor/modules.txt
	k8s.io/component-base: is replaced in go.mod, but not marked as replaced in vendor/modules.txt
	k8s.io/cri-api: is replaced in go.mod, but not marked as replaced in vendor/modules.txt
	k8s.io/csi-translation-lib: is replaced in go.mod, but not marked as replaced in vendor/modules.txt
	k8s.io/kube-aggregator: is replaced in go.mod, but not marked as replaced in vendor/modules.txt
	k8s.io/kube-controller-manager: is replaced in go.mod, but not marked as replaced in vendor/modules.txt
	k8s.io/kube-proxy: is replaced in go.mod, but not marked as replaced in vendor/modules.txt
	k8s.io/kube-scheduler: is replaced in go.mod, but not marked as replaced in vendor/modules.txt
	k8s.io/kubectl: is replaced in go.mod, but not marked as replaced in vendor/modules.txt
	k8s.io/kubelet: is replaced in go.mod, but not marked as replaced in vendor/modules.txt
	k8s.io/legacy-cloud-providers: is replaced in go.mod, but not marked as replaced in vendor/modules.txt
	k8s.io/metrics: is replaced in go.mod, but not marked as replaced in vendor/modules.txt
	k8s.io/node-api: is replaced in go.mod, but not marked as replaced in vendor/modules.txt
	k8s.io/sample-apiserver: is replaced in go.mod, but not marked as replaced in vendor/modules.txt
	k8s.io/sample-cli-plugin: is replaced in go.mod, but not marked as replaced in vendor/modules.txt
	k8s.io/sample-controller: is replaced in go.mod, but not marked as replaced in vendor/modules.txt

run 'go mod vendor' to sync, or use -mod=mod or -mod=readonly to ignore the vendor directory
FATA[0000] Failed to run operator locally: failed to build operator to run locally: failed to exec []string{"go", "build", "-o", "build/_output/bin/service-binding-operator-local", "-mod=vendor", "github.com/redhat-developer/service-binding-operator/cmd/manager"}: exit status 1 
make: *** [Makefile:349: local] Error 1
```

### PR DESCRIPTION
**Pull request by DhritiShikhar**
### Motivation

[1] Fixes issue #483 which is about failure to run operator locally through CLI `make local`.

### Changes

[1] Adds `vendor/modules.txt` file auto-generated by `go mod vendor`.

### Testing

[1] CLI `make local` should be success and operator should run locally.

### CODE REVIEW

**Comment by Avni-Sharma** [comment]
`make local ` seems to work for me locally without the fix,
Rather on running `go mod vendor` again on this PR , git diff shows the exclusion of the changes. 
Perhaps try running it again on master

**Comment by DhritiShikhar** [comment]
@Avni-Sharma Can you share your `vendor/modules.txt`?

**Comment by Avni-Sharma** [comment]
https://gist.github.com/Avni-Sharma/383f6160710505e2461b081e010a2139
The vendor/modules.txt was updated lately with the OLM update PR

**Comment by isutton** [comment]
Testing against a local cluster, `make local` indeed works as expected.

/lgtm
/approve

**Comment by pedjak** [comment]
I can also confirm that I can reproduce the issue on master, and this PR fixes it.

**Comment by akashshinde** [comment]
I got the same error mentioned in https://github.com/redhat-developer/service-binding-operator/issues/483, however running `go mode vendor` fixed the issue.

**Comment by Avni-Sharma** [comment]
Was on go 1.13, updated now to 1.14.3
PR works :+1:

**Pull request merged**
