### PR TITLE
make custom_env_var can reference the whole secret/configmap without using a slash

### PR DESCRIPTION
**Pull request by qibobo**
This PR is to fix the issue we reported in https://github.com/redhat-developer/service-binding-operator/issues/475#issuecomment-646114247.
@isutton 
Could you take a look at this PR? It need to be rebased after your PR https://github.com/redhat-developer/service-binding-operator/pull/515 is merged.

### CODE REVIEW

**Comment by isutton** [comment]
@qibobo I've rebased https://github.com/redhat-developer/service-binding-operator/pull/515 on upstream's master.

**Comment by qibobo** [comment]
@isutton I have rebase the code with master and verified the feature works.
Test steps:
1 Add annotations:
```
metadata:
  annotations:
    servicebindingoperator.redhat.io/status.secretName: binding:env:object:secret
    servicebindingoperator.redhat.io/status.secretName-url: binding:env:object:secret

```

2 create knative service as application
```
cat <<EOF | kubectl apply -f -
apiVersion: serving.knative.dev/v1
kind: Service 
metadata:
  name: knative-vcap
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "1"
    spec:
      containers:
        - image: docker.io/qibobo/go4autoscaler:latest
          ports:
          - containerPort: 8080
EOF

```

3 Create SBR
```
cat <<EOF | kubectl apply -f -
apiVersion: apps.openshift.io/v1alpha1
kind: ServiceBindingRequest
metadata:
  name: binding-request-vcap
spec:
  applicationSelector:
    resourceRef: knative-vcap
    group: serving.knative.dev 
    version: v1 
    resource: services 
  backingServiceSelectors:
    - group: ibmcloud.ibm.com
      version: v1alpha1
      kind: Binding
      resourceRef: thetranslator5
      envVarPrefix: serviceprefix
  customEnvVar:
    - name: VCAP_SERVICES
      value: '{"language-translator":[{"credentials":{{json .v1alpha1.ibmcloud_ibm_com.Binding.thetranslator5.status.secretName}},"name":"thetranslator5","plan":"standard"}]}'
    - name: TRANSLATOR_NAME
      value: "thetranslator5"
    - name: URL
      value: '{{.v1alpha1.ibmcloud_ibm_com.Binding.thetranslator5.status.secretName.url}}'
EOF
```
4 Check env injection:

```
SERVICEPREFIX_SECRET_IAM_ROLE_CRN=crn:v1:bluemix:public:iam::::serviceRole:Manager
SERVICEPREFIX_SECRET_APIKEY=XXXXXX
SERVICEPREFIX_SECRET_IAM_SERVICEID_CRN=crn:v1:bluemix:public:iam-identity::a/ef6a34810cbcd892507d3ebe01e3d95a::serviceid:ServiceId-471aa3de-daac-483a-9364-42fe0854a353
SERVICEPREFIX_SECRET_IAM_APIKEY_DESCRIPTION=Auto-generated for key 6142fe4b-5a7d-4951-8c64-b70433b1ccd3
SERVICEPREFIX_SECRET_URL=https://api.us-south.language-translator.watson.cloud.ibm.com/instances/b6cff0d7-dcfb-467d-9f75-7a044b6b15fd
SERVICEPREFIX_SECRET_IAM_APIKEY_NAME=thetranslator5

VCAP_SERVICES={"language-translator":[{"credentials":{"apikey":"XXXXXX","iam_apikey_description":"Auto-generated for key 6142fe4b-5a7d-4951-8c64-b70433b1ccd3","iam_apikey_name":"thetranslator5","iam_role_crn":"crn:v1:bluemix:public:iam::::serviceRole:Manager","iam_serviceid_crn":"crn:v1:bluemix:public:iam-identity::a/ef6a34810cbcd892507d3ebe01e3d95a::serviceid:ServiceId-471aa3de-daac-483a-9364-42fe0854a353","url":"https://api.us-south.language-translator.watson.cloud.ibm.com/instances/b6cff0d7-dcfb-467d-9f75-7a044b6b15fd"},"name":"thetranslator5","plan":"standard"}]}
URL=https://api.us-south.language-translator.watson.cloud.ibm.com/instances/b6cff0d7-dcfb-467d-9f75-7a044b6b15fd

```

**Comment by cdlliuy** [comment]
@isutton  , the test seems passed

**Comment by cdlliuy** [comment]
@DhritiShikhar @isutton ,  can you help to review?

**Pull request merged**
