### PR TITLE
Revert annotation handling mechanism to not use the original config map or secret resource name location

### LINKED ISSUE #485: Revert annotation handling mechanism to not use the original config map or secret resource name location
After #407 an undocumented behavior regarding annotations meant to extract config map and secret values has been unwillingly changed and needs to be reverted.

The annotations handling mechanism after #407 extracts the whole contents of the config map or secret to the same path where the config map or secret name has been stored (resulting in, for example, `.status.secretName.password` if `.data.password` is present in the associated resource) to workaround situations where two services might have a `password` field within different paths and might get shadowed, whereas before #407 it used to extract the contents to the root of the resulting object (for example, `.password`), imposing no issue whatsoever because there were only one service being declared in the binding.

For reference, see https://github.com/redhat-developer/service-binding-operator/issues/475#issuecomment-631291414.

### PR DESCRIPTION
**Pull request by isutton**
### Motivation

After #407 an undocumented behavior regarding annotations meant to extract
config map and secret values has been unwillingly changed and needs to be
reverted.

The annotations handling mechanism after #407 extracts the whole contents of
the config map or secret to the same path where the config map or secret name
has been stored (resulting in, for example, .status.secretName.password if
.data.password is present in the associated resource) to workaround
situations where two services might have a password field within different
paths and might get shadowed, whereas before #407 it used to extract the
contents to the root of the resulting object (for example, .password),
imposing no issue whatsoever because there were only one service being
declared in the binding.

Closes #485 

### Changes

This change reverts the behavior where the source path isn't expected in the
resulting environment variable name; for example, the excerpt below shows
annotations present in a resource CRD, as a JSON object:

```json
{
  "servicebindingoperator.redhat.io/status.connectionArguments.databaseName": "binding:env:attribute",
  "servicebindingoperator.redhat.io/status.connectionArguments.host": "binding:env:attribute",
  "servicebindingoperator.redhat.io/status.connectionArguments.port": "binding:env:attribute",
  "servicebindingoperator.redhat.io/status.connectionCredentials-password": "binding:env:object:secret",
  "servicebindingoperator.redhat.io/status.connectionCredentials-username": "binding:env:object:secret",
  "servicebindingoperator.redhat.io/status.externalConnectionArguments-databaseName": "binding:env:object:configmap",
  "servicebindingoperator.redhat.io/status.externalConnectionArguments-host": "binding:env:object:configmap",
  "servicebindingoperator.redhat.io/status.externalConnectionArguments-port": "binding:env:object:configmap"
}
```

Before the changes introduced in this PR, the following environment variables
are generated and encoded in the service binding intermediate secret, where
the issue can be seen where the string `STATUS_EXTERNALCONNECTIONARGUMENTS`
and `STATUS_CONNECTIONCREDENTIALS` can be read:

```
NAME            TYPE    KEY                                                                     VALUE
service-binding Opaque  DATABASE_CONFIGMAP_STATUS_EXTERNALCONNECTIONARGUMENTS_DATABASENAME      "db-name"
service-binding Opaque  DATABASE_CONFIGMAP_STATUS_EXTERNALCONNECTIONARGUMENTS_HOST              "database.prod.example.com"
service-binding Opaque  DATABASE_CONFIGMAP_STATUS_EXTERNALCONNECTIONARGUMENTS_PORT              "5432"
service-binding Opaque  DATABASE_CONNECTIONARGUMENTS_DATABASENAME                               "db-demo"
service-binding Opaque  DATABASE_CONNECTIONARGUMENTS_HOST                                       "192.168.1.100"
service-binding Opaque  DATABASE_CONNECTIONARGUMENTS_PORT                                       "5432"
service-binding Opaque  DATABASE_SECRET_STATUS_CONNECTIONCREDENTIALS_PASSWORD                   "hunter2"
service-binding Opaque  DATABASE_SECRET_STATUS_CONNECTIONCREDENTIALS_USERNAME                   "AzureDiamond"
```

After the changes introduced in this PR, the following environment variables
are produced (please observe the absence of the strings mentioned above):

```
NAME            TYPE    KEY                                             VALUE
service-binding Opaque  DATABASE_CONFIGMAP_DATABASENAME                 "db-name"
service-binding Opaque  DATABASE_CONFIGMAP_HOST                         "database.prod.example.com"
service-binding Opaque  DATABASE_CONFIGMAP_PORT                         "5432"
service-binding Opaque  DATABASE_CONNECTIONARGUMENTS_DATABASENAME       "db-demo"
service-binding Opaque  DATABASE_CONNECTIONARGUMENTS_HOST               "192.168.1.100"
service-binding Opaque  DATABASE_CONNECTIONARGUMENTS_PORT               "5432"
service-binding Opaque  DATABASE_SECRET_PASSWORD                        "hunter2"
service-binding Opaque  DATABASE_SECRET_USERNAME                        "AzureDiamond"
```

The same behavior can be seen when changing the annotations to include the entire object, secret or config map as well; for example, the three annotations below should produce the same environment variables as above:

```json
{
  "servicebindingoperator.redhat.io/status.connectionArguments": "binding:env:attribute",
  "servicebindingoperator.redhat.io/status.connectionCredentials": "binding:env:object:secret",
  "servicebindingoperator.redhat.io/status.externalConnectionArguments": "binding:env:object:configmap"
}
```

As can be observed above, the same extra information is present in the resulting secret:

```
NAME            TYPE    KEY                                                                     VALUE
service-binding Opaque  DATABASE_CONFIGMAP_STATUS_EXTERNALCONNECTIONARGUMENTS_DATABASENAME      "db-name"
service-binding Opaque  DATABASE_CONFIGMAP_STATUS_EXTERNALCONNECTIONARGUMENTS_HOST              "database.prod.example.com"
service-binding Opaque  DATABASE_CONFIGMAP_STATUS_EXTERNALCONNECTIONARGUMENTS_PORT              "5432"
service-binding Opaque  DATABASE_CONNECTIONARGUMENTS_DATABASENAME                               "db-demo"
service-binding Opaque  DATABASE_CONNECTIONARGUMENTS_HOST                                       "192.168.1.100"
service-binding Opaque  DATABASE_CONNECTIONARGUMENTS_PORT                                       "5432"
service-binding Opaque  DATABASE_SECRET_STATUS_CONNECTIONCREDENTIALS_PASSWORD                   "hunter2"
service-binding Opaque  DATABASE_SECRET_STATUS_CONNECTIONCREDENTIALS_USERNAME                   "AzureDiamond"
```

And, as expected, after the changes in this PR are applied:

```
NAME            TYPE    KEY                                             VALUE
service-binding Opaque  DATABASE_CONFIGMAP_DATABASENAME                 "db-name"
service-binding Opaque  DATABASE_CONFIGMAP_HOST                         "database.prod.example.com"
service-binding Opaque  DATABASE_CONFIGMAP_PORT                         "5432"
service-binding Opaque  DATABASE_CONNECTIONARGUMENTS_DATABASENAME       "db-demo"
service-binding Opaque  DATABASE_CONNECTIONARGUMENTS_HOST               "192.168.1.100"
service-binding Opaque  DATABASE_CONNECTIONARGUMENTS_PORT               "5432"
service-binding Opaque  DATABASE_SECRET_PASSWORD                        "hunter2"
service-binding Opaque  DATABASE_SECRET_USERNAME                        "AzureDiamond"
```

For further more details refer the CONTRIBUTING.md

### CODE REVIEW

**Comment by qibobo** [comment]
@isutton 
I went though this PR and my PR https://github.com/redhat-developer/service-binding-operator/pull/521. And I think they are not fixing the same issue.
They are all for that user can just set the annotation like "servicebindingoperator.redhat.io/status.connectionCredentials": "binding:env:object:secret" without requiring to set all fields of the secret into the annotation.

But this PR is for the normal env vars, but PR https://github.com/redhat-developer/service-binding-operator/pull/521 is for custom env vars. So I think they are not conflicted, right?

**Comment by cdlliuy** [comment]
@isutton ,  as discussed on the meeting,  can you help to move forward of this PR and #515,  so that we can add #521 on top of them?

**Comment by cdlliuy** [comment]
@isutton  I noticed #515 is updated . Will you merge #522 first?

**Pull request merged**
