### PR TITLE
Update examples with label selectors

### PR DESCRIPTION
**Pull request by baijum**
### Motivation

The example was not updated with #291 

### Changes

Update the example CR and CRD.

### Testing

No code change.

### CODE REVIEW

**Comment by sbose78** [comment]
Aren't these files supposed to be auto-generated when the Golang API is updated?

**Comment by baijum** [comment]
> Aren't these files supposed to be auto-generated when the Golang API is updated?

The CRD was auto-generated with a different file name: `apps.openshift.io_servicebindingrequests_crd.yaml`
I missed to commit it earlier. Now I copied to existing CRD.
Should I rename it to the default file name that is generated?

The CR should be updated manually.

**Comment by sbose78** [comment]
Yeah the default file name would be nice to have.

**Comment by sbose78** [comment]
In a different PR, I think we need to have some kind of (indirect) validation if the CRD inside `deploy/` isn't updated. @Avni-Sharma 's auto-release PR uses the yamls inside `/deploy` to generate releases, hence it's critical to ensure we catch misses using automation.

**Comment by baijum** [comment]
> Yeah the default file name would be nice to have.

@sbose78 I have renamed the file

**Comment by Avni-Sharma** [comment]
The community-operators one has the previous name https://github.com/operator-framework/community-operators/blob/master/community-operators/service-binding-operator/0.0.20/servicebindingrequests.apps.openshift.io.crd.yaml 
In the next release, we should be changing that

**Pull request merged**
