### PR TITLE
upgrade operator to 0.0.4

### PR DESCRIPTION
**Pull request by sbose78**
- move olm manifests to a flat manifests dir
- fix the incorrect operator image name url.
- new operator csv has `replaces: service-binding-operator.v0.0.1`

image

Validated by creating an `OperatorSource` and then a `Subscription`

image

### CODE REVIEW

**Comment by sbose78** [comment]
@DhritiShikhar 

I see these errors 

```
Pulling image "docker-registry.default.svc:5000/ci-op-bfyvpg1h/pipeline@sha256:bd5065efeb00ae2433378a1c7ae4af2bd868e6a7b1be8c155af29ed0a552f224" ...
error: open /tmp/build/inputs/openshift-ci/Dockerfile.registry.intermediate: no such file or directory
2019/06/27 18:36:46 Build bin succeeded after 2m26s
2019/06/27 18:36:46 Building service-binding-operator
2019/06/27 18:36:54 Build service-binding-operator failed, printing logs:
Pulling image "docker-registry.default.svc:5000/ci-op-bfyvpg1h/pipeline@sha256:06deb74a59808be4699273dba8c565fea249be54ad2cc56e3349731aca211901" ...
Pulling image "docker-registry.default.svc:5000/ci-op-bfyvpg1h/pipeline@sha256:bd5065efeb00ae2433378a1c7ae4af2bd868e6a7b1be8c155af29ed0a552f224" ...
error: open /tmp/build/inputs/openshift-ci/Dockerfile.deploy: no such file or directory
```

These look unrelated to this change moreover `openshift-ci/Dockerfile.deploy` was present in devconsole-operator. Did you commit any of these into our CI scripts by mistake?

**Comment by sbose78** [comment]
funny, operator-courier doesn't all problems 

```
 error creating csv service-binding-operator.v0.0.3:
        ClusterServiceVersion.operators.coreos.com
        "service-binding-operator.v0.0.3" is invalid: []: Invalid value:
        map[string]interface {}{"kind":"ClusterServiceVersion",
        "apiVersion":"operators.coreos.com/v1alpha1",
        "metadata":map[string]interface
        {}{"name":"service-binding-operator.v0.0.3",
        "namespace":"openshift-operators",
        "creationTimestamp":"2019-06-27T18:58:39Z",
        "annotations":map[string]interface
        {}{"containerImage":"quay.io/redhat-developer/app-binding-operator:v0.0.3",
        "description":"An operator to support binding capabilities between
        imported apps and operator backed services",
        "alm-examples":"[{\"apiVersion\":\"apps.openshift.io/v1alpha1\",\"kind\":\"ServiceBindingRequest\",\"metadata\":{\"name\":\"example-servicebindingrequest\"},\"spec\":{\"applicationSelector\":{\"matchLabels\":{\"connects-to\":\"postgres\",\"environment\":\"production\"},\"resourceKind\":\"Deployment\"},\"backingSelector\":{\"resourceName\":\"database.example.org\",\"resourceVersion\":\"v1alpha1\"}}}]",
        "capabilities":"Basic Install"}, "generation":1,
        "uid":"9322b8c1-990d-11e9-b243-0e7a0685431e"},
        "spec":map[string]interface {}{"install":map[string]interface
        {}{"strategy":"deployment", "spec":map[string]interface
        {}{"deployments":[]interface {}{map[string]interface
        {}{"name":"service-binding-operator", "spec":map[string]interface
        {}{"template":map[string]interface {}{"metadata":map[string]interface
        {}{"labels":map[string]interface {}{"name":"service-binding-operator"}},
        "spec":map[string]interface {}{"containers":[]interface
        {}{map[string]interface {}{"imagePullPolicy":"Always",
        "name":"service-binding-operator", "resources":map[string]interface
        {}{}, "command":[]interface {}{"service-binding-operator"},
        "env":[]interface {}{map[string]interface {}{"name":"WATCH_NAMESPACE",
        "valueFrom":map[string]interface {}{"fieldRef":map[string]interface
        {}{"fieldPath":"metadata.annotations['olm.targetNamespaces']"}}},
        map[string]interface {}{"valueFrom":map[string]interface
        {}{"fieldRef":map[string]interface {}{"fieldPath":"metadata.name"}},
        "name":"POD_NAME"}, map[string]interface {}{"name":"OPERATOR_NAME",
        "value":"service-binding-operator"}},
        "image":"quay.io/redhat-developer/app-binding-operator:v0.0.3"}},
        "serviceAccountName":"service-binding-operator"}}, "replicas":1,
        "selector":map[string]interface {}{"matchLabels":map[string]interface
        {}{"name":"service-binding-operator"}}, "strategy":map[string]interface
        {}{}}}}, "permissions":[]interface {}{map[string]interface
        {}{"serviceAccountName":"service-binding-operator", "rules":[]interface
        {}{map[string]interface {}{"apiGroups":[]interface {}{""},
        "resources":[]interface {}{"pods", "services", "endpoints",
        "persistentvolumeclaims", "events", "configmaps", "secrets"},
        "verbs":[]interface {}{"*"}}, map[string]interface
        {}{"apiGroups":[]interface {}{"apps"}, "resources":[]interface
        {}{"deployments", "daemonsets", "replicasets", "statefulsets"},
        "verbs":[]interface {}{"*"}}, map[string]interface
        {}{"apiGroups":[]interface {}{"monitoring.coreos.com"},
        "resources":[]interface {}{"servicemonitors"}, "verbs":[]interface
        {}{"get", "create"}}, map[string]interface
        {}{"resourceNames":[]interface {}{"service-binding-operator"},
        "resources":[]interface {}{"deployments/finalizers"},
        "verbs":[]interface {}{"update"}, "apiGroups":[]interface {}{"apps"}},
        map[string]interface {}{"apiGroups":[]interface {}{"apps.openshift.io"},
        "resources":[]interface {}{"*"}, "verbs":[]interface {}{"*"}},
        map[string]interface {}{"apiGroups":[]interface {}{""},
        "resources":[]interface {}{"*"}, "verbs":[]interface {}{"get"}}}}}}},
        "version":"0.0.3", "customresourcedefinitions":map[string]interface
        {}{"owned":[]interface {}{map[string]interface
        {}{"name":"servicebindingrequests.apps.openshift.io",
        "version":"v1alpha1", "kind":"ServiceBindingRequest"}}},
        "apiservicedefinitions":map[string]interface {}{},
        "maintainers":[]interface {}{map[string]interface {}{"name":"Shoubhik
        Bose", "email":"shbose@redhat.com"}}, "links":[]interface
        {}{map[string]interface {}{"name":"Source Code",
        "url":"https://github.com/redhat-developer/service-binding-operator"}},
        "replaces":"service-binding-operator.v0.0.1", "maturity":"alpha",
        "displayName":"Operator Service Binding Operator",
        "description":"Placeholder description", "provider":map[string]interface
        {}{"name":"Red Hat, Inc."}, "installModes":[]interface
        {}{map[string]interface {}{"type":"OwnNamespace", "supported":true},
        map[string]interface {}{"type":"SingleNamespace", "supported":true},
        map[string]interface {}{"type":"MultiNamespace", "supported":false},
        map[string]interface {}{"type":"AllNamespaces", "supported":true}}}}:
        validation failure list:

        spec.customresourcedefinitions.owned.displayName in body is required

        spec.customresourcedefinitions.owned.description in body is required
```

**Comment by sbose78** [comment]
fixed it, and updated description.

**Comment by baijum** [comment]
> These look unrelated to this change moreover `openshift-ci/Dockerfile.deploy` was present in devconsole-operator. Did you commit any of these into our CI scripts by mistake?

There is a PR (#35) from @DhritiShikhar with the necessary changes. The CI configuration was updated to test it. But that is failing still. Please use your admin privilege to merge your PR.

**Comment by sbose78** [comment]
Ah OK.

So, how about
1. I merge this PR with the tested/released manifests
2. @DhritiShikhar could refactor #35 to remove the manifest changes, and then we could merge that?

**Comment by baijum** [comment]
> Ah OK.
> 
> So, how about
> 
> 1. I merge this PR with the tested/released manifests
> 2. @DhritiShikhar could refactor #35 to remove the manifest changes, and then we could merge that?

Yes, please go ahead with merge.

**Comment by sbose78** [comment]
Thanks @baijum .

**Comment by DhritiShikhar** [comment]
@sbose78 
[1] My PR hasn't been merged yet. There are no other commits by me.
[2] Yes. I will refactor my PR to remove the manifest changes.

**Pull request merged**
