### PR TITLE
Ensure MountPathPrefix is optional

### PR DESCRIPTION
**Pull request by baijum**
Refer https://issues.redhat.com/browse/APPSVC-320

### CODE REVIEW

**Comment by isutton** [comment]
Isn't it required to run `make generate-k8s` to update the generated code?

**Comment by sbose78** [comment]
> Isn't it required to run make generate-k8s to update the generated code?

Yes!

**Comment by sbose78** [comment]
@baijum , could we address the feedback and get this in ?

**Comment by baijum** [comment]
I ran `make generate-k8s` and `make generate-openapi`, but it's not making any difference. If anyone can run it locally with the change in this PR, that would be helpful.

**Comment by baijum** [comment]
The struct tag `omitempty` was already making the field as optional. So, this change is redundant. But for consistency, we can merge this PR.

**Pull request merged**
