### PR TITLE
Remove flaky test `TestAddSchemesToFramework/end-to-end/scenario-sbr-app-db`

### PR DESCRIPTION
**Pull request by pedjak**

### CODE REVIEW

**Comment by DhritiShikhar** [comment]
The e2e on this PR is failing now for `scenario-app-sbr-db`

**Comment by DhritiShikhar** [comment]
@pmacik @pedjak Why approve the PR? The e2e tests are still failing.

**Comment by pmacik** [comment]
> @pmacik @pedjak Why approve the PR? The e2e tests are still failing.

@DhritiShikhar All of the tests passed, but it looks we missed one additional flaky test, that passed this time, but failed on the final pre-merge round... I've disabled it as well, so we are now aligned with #556 where we originally disabled the very same scenarios.

**Pull request merged**
