### PR TITLE
use 0.0.23 CSV version as template when generating a new one

### PR DESCRIPTION
**Pull request by pedjak**
### Motivation

Generated CSV does not contain the following fields:

* categories
* description
* icon

and they are required for publishing the operator to community hub. Hence, we are adding them manually.

### Changes

Use 0.0.23 CSV version as template when generating a new one. `service-binding-operator.v0.0.23.clusterserviceversion.yaml` contains a curated set of fields like proper description, maintainer list, icon, etc.

### Testing

```
make push-to-manifest-repo
```
The generated manifest can be submitted to community-operator project without manual editing.

### CODE REVIEW

**Comment by DhritiShikhar** [comment]
@pedjak The `0.0.23` CSV -> https://github.com/redhat-developer/service-binding-operator-manifests/blob/master/0.0.23/service-binding-operator.v0.0.23.clusterserviceversion.yaml

does not have following fields:

- categories
- repository
- support
- icon

and does not have the correct value of these fields:
- links
- maintainers

**Comment by Avni-Sharma** [comment]
I believe he is checking from olm-catalog

**Comment by pedjak** [comment]
@DhritiShikhar When I said `service-binding-operator.v0.0.23.clusterserviceversion.yaml`, I was referring https://github.com/redhat-developer/service-binding-operator/blob/master/deploy/olm-catalog/service-binding-operator/0.0.23/service-binding-operator.v0.0.23.clusterserviceversion.yaml - it is used as the template and it contains:

* [categories](https://github.com/redhat-developer/service-binding-operator/blob/master/deploy/olm-catalog/service-binding-operator/0.0.23/service-binding-operator.v0.0.23.clusterserviceversion.yaml#L31)
* [repository](https://github.com/redhat-developer/service-binding-operator/blob/master/deploy/olm-catalog/service-binding-operator/0.0.23/service-binding-operator.v0.0.23.clusterserviceversion.yaml#L33)
* [support](https://github.com/redhat-developer/service-binding-operator/blob/master/deploy/olm-catalog/service-binding-operator/0.0.23/service-binding-operator.v0.0.23.clusterserviceversion.yaml#L34)
* icons value is generated on the fly from https://github.com/redhat-developer/service-binding-operator/blob/master/assets/icon/red-hat-logo.svg, with `make push-to-manifest-repo`
* [links](https://github.com/redhat-developer/service-binding-operator/blob/master/deploy/olm-catalog/service-binding-operator/0.0.23/service-binding-operator.v0.0.23.clusterserviceversion.yaml#L183)
* [maintainers](https://github.com/redhat-developer/service-binding-operator/blob/master/deploy/olm-catalog/service-binding-operator/0.0.23/service-binding-operator.v0.0.23.clusterserviceversion.yaml#L186)

Please check the generated manifest.

**Pull request merged**
