### PR TITLE
Add acceptance test scenario: Bind 2 backing services to a single application.

### PR DESCRIPTION
**Pull request by pratikjagrut**
### Motivation

Acceptance test to verify binding two backing service to a single application.
https://issues.redhat.com/projects/APPSVC/issues/APPSVC-640

### Testing

`make test-acceptance`

To run acceptance test make sure you're using `OC version >=4.5`

### CODE REVIEW

**Comment by pratikjagrut** [comment]
Forced push for rebasing the PR.

**Comment by Avni-Sharma** [comment]
Hi @pratikjagrut The Acceptance criteria in JIRA shows ` set matching labels on it` . Just wanted to confirm if resourceRef would suffice or match Labels is needed?

**Comment by pratikjagrut** [comment]
> Hi @pratikjagrut The Acceptance criteria in JIRA shows ` set matching labels on it` . Just wanted to confirm if resourceRef would suffice or match Labels is needed?

@Avni-Sharma Resource ref will be sufficient.

**Comment by pratikjagrut** [comment]
Force pushed in favour of squashed commit.

**Pull request merged**
