### PR TITLE
Add missing manifest and make targets for MySQL Cluster Sample

### PR DESCRIPTION
**Pull request by growi**
issue: #1124

# Changes

Added petclinic-mysqlcluster-binding.yaml containing a manifest for the ServiceBinding.
Added the following  make targets:
- deploy-mysqlcluster: to create the cluster
- deploy-app-mysql: to create the modified Spring-Petclinic Application
- bind-mysqlcluster: to create the ServiceBinding
- unbind-mysqlcluster: to delete the ServiceBinding

# Submitter Checklist

As the author of this PR, please check off the items in this checklist:

- [ ] [Docs](https://github.com/redhat-developer/service-binding-operator/blob/master/CONTRIBUTING.md#docs) 
  included if any changes are user facing
- [X] [Tests](https://github.com/redhat-developer/service-binding-operator/blob/master/CONTRIBUTING.md#tests)
  included if any functionality added or changed. For bugfixes please include tests that can catch regressions
- [ ] All acceptance test scenarios included in the PR which verifies a bugfix or a requested feature reported by a non-member are tagged with `@external-feedback` tag.
- [X] Follows the [commit message standard](https://github.com/redhat-developer/service-binding-operator/blob/master/CONTRIBUTING.md#commits)

### CODE REVIEW

**Comment by pmacik** [comment]
@growi Thanks for your PR, however your branch is based on master that had CI broken, and which was recently fixed by https://github.com/redhat-developer/service-binding-operator/pull/1127. That is why all most of the PR checks fails. Please rebase on top of the current master to make the CI checks working again. So that your PR can be merged.

**Comment by growi** [comment]
@pmacik I rebased to the current master.

**Pull request merged**
