### PR TITLE
Upgrade go version from 1.14 to 1.15

### LINKED ISSUE #657: Upgrade go version to 1.15

### PR DESCRIPTION
**Pull request by Avni-Sharma**
Upgrade go version from 1.14 to 1.15 .
New golang version now also available in https://github.com/openshift/release/tree/master/projects/origin-release/golang-1.15

fixes #657

### CODE REVIEW

**Comment by baijum** [comment]
Upgrading to Go 1.15 is not risky. Since we are focusing on first preview release, we can do this after that.

**Comment by sbose78** [comment]
On that note, should be start labelling items with a specific version to indicate post v0.3 items?

**Comment by DhritiShikhar** [comment]
@sbose78 +1 on labelling items for v0.4

**Comment by Avni-Sharma** [comment]
@pedjak Any targeted timeline or a specific release for which we might have to get this in?

**Review by pedjak — APPROVED** [review]

**Pull request merged**
