### PR TITLE
Replace docker by podman.

### PR DESCRIPTION
**Pull request by pmacik**
This PR:
* Replaces `docker` by `podman` (and `buildah`) tools. The reason is that OpenShift do not ship with Docker. The `podman` (and `buildah`) are used by OpenShift instead, as it is part of it, so we should, too.

### CODE REVIEW

**Comment by Avni-Sharma** [comment]
Hi @pmacik. Can you rebase the PR.

**Comment by pmacik** [comment]
> Hi @pmacik. Can you rebase the PR.

@Avni-Sharma Just rebased.

**Pull request merged**
