### PR TITLE
Remove sdk generated build dir

### PR DESCRIPTION
**Pull request by sbose78**
I don't think we use it anywhere :)

### CODE REVIEW

**Comment by baijum** [comment]
This is required for `operator-sdk up local`:
```
$ operator-sdk up local
INFO[0000] Running the operator locally.                
INFO[0000] Using namespace default.                     
FATA[0000] must run command in project root dir: project structure requires build/Dockerfile 
```

**Comment by sbose78** [comment]
Ah OK, then need to add a tiny Readme in that directory.

**Comment by Avni-Sharma** [comment]
https://github.com/redhat-developer/service-binding-operator/pull/277

**Pull request closed without merging**
