### PR TITLE
Upgrade operator-sdk version to 0.17.0 in CI and Dockerfile

### PR DESCRIPTION
**Pull request by Avni-Sharma**
Follow up to https://github.com/redhat-developer/service-binding-operator/pull/798

Testing-
Passing tests in CI

### CODE REVIEW

**Comment by Avni-Sharma** [comment]
Hi @pedjak Is there any way wherein we can retrigger travis build with a command here?

**Comment by isutton** [comment]
Last upgrade we have regarding the operator-sdk it didn't go so smooth; can you confirm no other changes are required to upgrade the operator-sdk version?

**Comment by Avni-Sharma** [comment]
No other changes required

**Comment by pedjak** [comment]
Got obsolete by https://github.com/redhat-developer/service-binding-operator/pull/848, closing.

**Pull request closed without merging**
