### PR TITLE
set version to 0.1.0

### PR DESCRIPTION
**Pull request by pedjak**
Preparations for 0.1.0 release

### CODE REVIEW

**Comment by sbose78** [comment]
I'll let @DhritiShikhar weigh in on whether https://issues.redhat.com/browse/APPSVC-9 could be considered part of this?

I'm fine if it's not :) Wanted to check.

**Comment by DhritiShikhar** [comment]
@sbose78 @pedjak Yes generic binding can be a part of this. Need 1-2 days.

**Comment by sbose78** [comment]
Dhriti, are you okay if we skip your PR for 0.1.0? We'll take in 0.1.1 ?

**Comment by DhritiShikhar** [comment]
@sbose78 okay. Yes.

**Comment by sbose78** [comment]
@Avni-Sharma @baijum @DhritiShikhar does this look good to you with respect to bumping the version in our manifests?

**Pull request merged**
