### PR TITLE
Test to verify binding a single backing service with two individual applications

### PR DESCRIPTION
**Pull request by DhritiShikhar**
Story -> https://jira.coreos.com/browse/APPSVC-246

### CODE REVIEW

**Comment by pmacik** [comment]
@DhritiShikhar Your PR actually adds a unit test, which is completely fine and cool. However, the [story](https://jira.coreos.com/browse/APPSVC-246) is about adding an end-2-end test.

**Comment by DhritiShikhar** [comment]
@pmacik I have updated the Jira story

**Comment by pmacik** [comment]
> @pmacik I have updated the Jira story

@DhritiShikhar Wait, my point was not about the story being wrong, but to let you know that this PR (while it adds a unit test) do not implements the story... The original story was correct - to add an e2e test)

**Comment by pmacik** [comment]
@DhritiShikhar And, (hopefully) to avoid further confusion - This PR is completely valid - it just adds a slightly different thing than the original story.

**Comment by ldimaggi** [comment]
This comment is to late as the PR has been merged - but - an interesting negative test would be to track the error (if any returned) if a user inadvertently bound the same backing service more than once.

**Pull request merged**
